[package]
name = "lua-monologue-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.9"
prost = "0.11"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres"] }


[build-dependencies]
tonic-build = "0.9"